import requests
import json
import pandas as pd
import datetime

BASE_URL = 'https://api.figshare.com/v2'

# Read institution IDs from a CSV generated by oaimphFig.py
institutions_csv = 'institutionListOAI.csv'  # Update path if needed
df_insts = pd.read_csv(institutions_csv)
institution_ids = df_insts['instution_id'].dropna().unique().tolist()

all_metadata = []
all_stats = []

for institution_id in institution_ids:
    print(f"Processing institution ID: {institution_id}")
    results = []
    # Step 1: Harvest all datasets for the institution
    for page in range(1, 1000):
        query = {
            "institution": institution_id,
            "search_for": ":defined_type_name:dataset"
        }
        response = requests.post(
            f"{BASE_URL}/articles/search?page_size=1000&page={page}",
            json=query
        )
        items = json.loads(response.content)
        if not items:
            break
        results.extend(items)
        print(f"Institution {institution_id} - Page {page}: {len(items)} items retrieved")
    print(f"Institution {institution_id}: Total items harvested: {len(results)}")

    # Step 2: Extract item IDs
    item_ids = [item['id'] for item in results if 'id' in item]

    # Step 3: Gather statistics and full metadata for each item
    for item_id in item_ids:
        # Get full metadata
        meta_resp = requests.get(f"{BASE_URL}/articles/{item_id}")
        metadata = meta_resp.json()
        metadata['institution_id'] = institution_id  # Track which institution
        all_metadata.append(metadata)
        # Get statistics using the public_html URL as in oaimphFig.py
        url_public_html = metadata.get('url_public_html', '')
        stats_url = ''
        stats = {}
        if url_public_html:
            url_parts = url_public_html.split('//')[1].split('.')
            # Try first part
            stats_url_1 = f"https://stats.figshare.com/{url_parts[0]}/total/views/article/{item_id}"
            stats_resp_1 = requests.get(stats_url_1)
            if stats_resp_1.status_code == 200:
                stats = stats_resp_1.json()
                stats_url = stats_url_1
                if stats.get('totals', 0) > 0:
                    pass  # Use this stats_url
                else:
                    # Try the second part if available
                    if len(url_parts) > 1:
                        stats_url_2 = f"https://stats.figshare.com/{url_parts[1]}/total/views/article/{item_id}"
                        stats_resp_2 = requests.get(stats_url_2)
                        if stats_resp_2.status_code == 200:
                            stats2 = stats_resp_2.json()
                            if stats2.get('totals', 0) > 0:
                                stats = stats2
                                stats_url = stats_url_2
            else:
                # Fallback to old style if public_html fails
                stats_url = f"https://stats.figshare.com/item/total/views/article/{item_id}"
                stats_resp = requests.get(stats_url)
                if stats_resp.status_code == 200:
                    stats = stats_resp.json()
        else:
            # Fallback if no public_html
            stats_url = f"https://stats.figshare.com/item/total/views/article/{item_id}"
            stats_resp = requests.get(stats_url)
            if stats_resp.status_code == 200:
                stats = stats_resp.json()
        stats['item_id'] = item_id
        stats['institution_id'] = institution_id
        stats['stats_url'] = stats_url
        all_stats.append(stats)
        print(f"Processed item {item_id} for institution {institution_id}")

# Step 4: Save metadata and stats to CSV
meta_df = pd.DataFrame(all_metadata)
stats_df = pd.DataFrame(all_stats)
today = datetime.datetime.now().strftime("%Y-%m-%d")
meta_df.to_csv(f"figshare_metadata_ALL_{today}.csv", index=False)
stats_df.to_csv(f"figshare_stats_ALL_{today}.csv", index=False)
print("All metadata and statistics saved to CSV files.")